#! /usr/bin/env zsh

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Manu Phatak <bionikspoon@gmail.com>
#

if [ $TERM = "xterm" ]
then
    export TERM=xterm-256color
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
